name: Create a pull request for QA

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
        
    - run: npm ci
    - run: npm run build --if-present
    - name: Create a release pull request
      env:
        GITHUB_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      run: |
        ./cli/index.js uiur/github-pr-release
